@shipment_api_host_address = http://localhost:3001

## create pricing 
POST {{shipment_api_host_address}}/pricing
Content-Type: application/json

{
  "type": "fragile",
  "price": 1.0
}

### get all pricing
GET {{shipment_api_host_address}}/pricing
Accept: application/json

### get single pricing by id
GET {{shipment_api_host_address}}/pricing/67a47e7220effd1cb99be34a
Accept: application/json

### get single pricing by type
GET {{shipment_api_host_address}}/pricing/type/fragile
Accept: application/json


### update pricing
PATCH {{shipment_api_host_address}}/pricing/67a47e7220effd1cb99be34a
Content-Type: application/json

{
  "price": 5.0
}

### delete pricing
DELETE {{shipment_api_host_address}}/pricing/67a47e6d20effd1cb99be347
Accept: application/json

### calculate shipping cost
POST {{shipment_api_host_address}}/shipment/calculate
Content-Type: application/json

{
  "weight": 10,
  "distance": 100,
  "type": "fragile"
}
